---
version: '3.6'

services:
  servinit-docs:
    container_name: servinit-docs
    image: servinit-docs:latest
    build:
      context: ..
      dockerfile: ./docsify/Dockerfile
    ports:
    - 6007:80
    restart: unless-stopped
